### ISSUE TITLE
The jpackage/jpackageImage tasks should be able to produce multiple installers

### ISSUE THREAD

**Issue by nemphys** [beryx/badass-jlink-plugin#115]
Since it is possible to produce images for more than one platform (using targetPlatform in the jlink task configuration), it would be nice to have the option to produce more than one jpackage image/installer using a similar option structure.

**Comment by siordache** [comment]
I didn't add such an option because in contrast to jlink, jpackage is not able to produce installers for other platforms. For example, to create an installer for Linux, you must run jpackage on a Linux machine. You cannot do it on a Windows or Mac platform. You are not even able to create a 32-bit Windows installer on a 64-bit Windows machine..
If you need to create installers for more than one platform, it's probably better **not** to use targetPlatform. Instead, you run the same build on different machines (for example, using [GitHub Actions](https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idruns-on))

**Comment by nemphys** [comment]
Right, I remember discovering this in the past, but apparently it was a long time ago, or I am getting old :-)

Closing this, hoping that one day jpackage will support cross platform builds
