### ISSUE TITLE
Task jlinkZip options to compress?

### ISSUE THREAD

**Issue by Yafei-W** [beryx/badass-jlink-plugin#142]
The task jlinkZip just seems to package files and directories into a zip file without compression.  Is there an option to do that?  In my case using independent zip program I can get close to 50% compression ratio.

**Comment by siordache** [comment]
The jlinkZip task uses [ant.zip](https://ant.apache.org/manual/Tasks/zip.html), which compresses the files by default. On my projects the resulting archive is always compressed.

What independent zip program did you use?

I would like to see the sizes of the archives produced by jlinkZip on your project, if you add the following snippet to your build.gradle:

```
tasks.jlinkZip.doLast {
    ant.zip(basedir: imageDir,
        destfile: "$buildDir/image-uncompressed.zip",
        duplicate: 'fail',
        update: false,
        compress: false)
    ant.zip(basedir: imageDir,
        destfile: "$buildDir/image-compressed-default.zip",
        duplicate: 'fail',
        update: false,
        compress: true)
    ant.zip(basedir: imageDir,
        destfile: "$buildDir/image-compressed-level9.zip",
        duplicate: 'fail',
        update: false,
        compress: true,
        level: 9)
}
```

For reference, adding the above code to one of my projects, I got the following archive sizes:

```
44.022.142 image.zip
58.283.798 image-uncompressed.zip
44.019.102 image-compressed-default.zip
43.981.237 image-compressed-level9.zip
```

In my case, the size differences between the compressed and the uncompressed archives are not very big, because I configured the compression options in the `jlink` block of my build script:
```
jlink {
    options = ['--strip-debug', '--compress', '2', '--no-header-files', '--no-man-pages']
    ....
}
```

**Comment by Yafei-W** [comment]
Hi siordache,

It works fine now.  Might be that during build setup, something else got zipped in as I was building for three platforms with JFX and JFX web.

Thanks.
