### ISSUE TITLE
exclude awt, swing, ...

### ISSUE THREAD

**Issue by kurt-o-sys** [beryx/badass-jlink-plugin#27]
I'm trying this plugin, and I really like it a lot... I seem to have a problem with the generated image though: it generates a 'modules' library, but that one seems to contain a lot of java modules which are absolutely not necessary by the application. I'm embedding vert.x, which is a server side library, and the modules include libraries like swing and awt (amongst others I don't really want)

Why would that be? Thx.

**Comment by siordache** [comment]
Swing and AWT are included in the [java.desktop](https://docs.oracle.com/en/java/javase/11/docs/api/java.desktop/module-summary.html) module. If your application requires this module (for example, because it uses directly or indirectly one of the classes in the java.beans package), all other packages available in this module will also appear in your runtime image.
There is no way to exclude Swing and AWT if your application needs the java.desktop module, The Java Module System works only with whole modules, not with fragments.

**Comment by kurt-o-sys** [comment]
so, probably, it's about that java.beans thing... The app doesn't need all this stuff, but maybe the library has some dependencies which lead to the java.beans package. OK, thx. Will try to find out.
