### ISSUE TITLE
Add options for module and merged module archive name

### ISSUE THREAD

**Issue by nemphys** [beryx/badass-jlink-plugin#50]
With the current version of the plugin, the jars produced in the (jlinkjars directory) for the base module and the merged module and named after the module names (moduleName/merged ModuleName settings).
It would be nice to have an option similar to archiveBaseName, so that the produced files are named according to it.

**Comment by siordache** [comment]
I will add these options in the next release (planned for the beginning of May).

**Comment by siordache** [comment]
In 2.10.3, the module and merged module archives are named in accordance with `archiveBaseName`. I think that's better than providing a separate option. The plugin already has a lot of options and the archives produced in the _jlinkjars_ directory are only temporary files used as input for the `jlink` tool, but they don't appear in the final image. Is it ok for you?

**Comment by nemphys** [comment]
I have no problem with this change (though the optimal solution would be to also have a setting for the 
 merged module archive name suffix, which now seems to be ".merged.module").

But, now that you mentioned it, I have been meaning to ask: is there any chance to consider an option *not* to merge *all* application jars together with the jdk modules inside the (huge) "modules" file by jlink?

I was thinking of a setup where just the jdk/javafx/(etc core) java modules are merged in the new image by jlink, with all *application* modules/jars (including the merged module) in a separate directory (unmerged).
This way, it might be possible to preserve the usefulness of jlink, while also preserving the ability to use smart update solutions like eg. update4j (https://github.com/update4j/update4j).

**Comment by siordache** [comment]
@nemphys Sorry for my late reply. 

> I was thinking of a setup where just the jdk/javafx/(etc core) java modules are merged in the new image by jlink, with all application modules/jars  (including the merged module) in a separate directory (unmerged).

I was wondering why the names of the base and merged module are important to you. Now I understand and it definitely makes sense. I will try to add support for this use case in the next version.

A more general setup would include the approaches taken by the [badass-runtime-plugin](https://badass-runtime-plugin.beryx.org/releases/latest/) and the [moditect-gradle-plugin](https://github.com/moditect/moditect-gradle-plugin). It would allow to:
- mix classpath and module-path
- specify which artifacts should be included in or excluded from the merged module
- specify which modules to include in the image created by jlink (that is, in the huge "modules" file)
- specify which of the artifacts not included in the huge "modules" file should be put on the classpath and which ones on the module-path
- generate and add module descriptors to some or all non-modular artifacts in your dependency graph (as [ModiTect](https://github.com/moditect/moditect-gradle-plugin#adddependenciesmoduleinfo)  does)

It would require some work to cover all possible use cases and make sure that other tasks (such as `jpackage`) still work properly. Due to lack of time, I will not work on this general solution (at least, not in the next couple of months), but I described it here in case someone wants to contribute it.

**Comment by nemphys** [comment]
This sounds great and a complete implementation would indeed turn this module into a Swiss army knife for jigsaw projects.
Do you think that it would be possible to at least implement the 3rd part ("specify which modules to include in the image created by jlink") anytime soon?

**Comment by siordache** [comment]
I will first provide a more limited version of this, where you can choose between including all modules or only the JRE modules. It should be available by the end of this week.

**Comment by nemphys** [comment]
This is great news, looking forward to testing it.

**Comment by siordache** [comment]
Implemented in 2.13.0. 

I also managed to provide support for specifying which modules to include in the image created by jlink. See the [documentation of the customImage block](https://badass-jlink-plugin.beryx.org/releases/latest/#_customimage).

The newly introduced property `mergedModuleJarName` allows you to configure the name of the JAR file containing the merged module.

Give it a try!

**Comment by nemphys** [comment]
Thank you for the fast response, I am closing this since it is resolved.
I am currently testing the customImage functionality (and having a hard time with it for the moment), I will probably open a new issue for the problems I am facing there.

**Comment by mordechaim** [comment]
Nice to see my project [update4j](https://github.com/update4j/update4j) part of a discussion, thanks 😊
