### ISSUE TITLE
Module java.xml.bind not found although dependency is available

### ISSUE THREAD

**Issue by rraumberger** [beryx/badass-jlink-plugin#56]
Hi,
I am trying to use this plugin for our project but it seems that the dependencies to jersey-server and jakarta.xml.bind-api break the "createMergedModule" task.
```
> Task :test:createMergedModule FAILED
<path>/test/build/jlinkbase/tmpjars/test.merged.module/module-info.java:72: error: module not found: java.xml.bind
    requires java.xml.bind;
```

I was able to reproduce this with the below `build.gradle`.
```
plugins {
    id 'java-library-distribution'
    id 'org.beryx.jlink' version '2.10.3'
}

ext.moduleName = 'test'
mainClassName = 'test.Test'

dependencies {
    implementation "org.glassfish.jersey.core:jersey-server:2.28"
    implementation "jakarta.xml.bind:jakarta.xml.bind-api:2.3.2"
}

jar {
    inputs.property('mainClassName', mainClassName)
    doLast {
        exec {
            executable = 'jar'
            args = [
                '--update', '--file', "$archiveFile.orNull",
                '--main-class', "$mainClassName"
            ]
        }
    }

    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
}

jlink {
    options = ['--strip-debug', '--compress', '2', '--no-header-files', '--no-man-pages']
}
```

It seems to me, that "prepareMergedJarsDir" never copied "jakarta.xml.bind-api" to "jlinkjars"  even though it is a full fledged module. Nor was the content extracted to "mergedJars".

Am I missing some plugin configuration, or did I encounter a bug?

Kind regards.

**Comment by mwkroening** [comment]
I think I encountered the same problem. Solution: https://github.com/beryx/badass-jlink-plugin/issues/38#issuecomment-476582381

**Comment by mwkroening** [comment]
In the Groovy syntax you are using it would be:
```groovy
jlink {
    options = ['--bind-services', '--strip-debug', '--compress', '2', '--no-header-files', '--no-man-pages']
}
```

I am not sure if that will solve your problem. I just found this issue to look similar to the one I had.

**Comment by rraumberger** [comment]
I agree. I looks rather similar. Unfortunately, "--bind-services" regardless of syntax does not solve this issue.

**Comment by siordache** [comment]
@rraumberger It's most likely a bug. I will provide a fix in the next days.

**Comment by siordache** [comment]
@rraumberger In 2.10.4 I fixed a bug that produced incorrect 'uses' directives in some situations. Use this new version.

There are a few other things you need to do in order to solve your problem. First, as @mwkroening suggested, use '--bind-services'.

For your application, the plugin is not able to detect all modules required by the merged module. This is due to dependencies on modules that were previously part of the JDK (such as `java.xml.bind`) but were removed in Java 11. Such dependencies are not configured in the POM of the jakarta libraries. You can fix this by force-merging the jakarta libraries.

The plugin is not always able to detect all services used by an application. In such cases, it is necessary to specify these services explicitly in the `mergedModule` block.

So try to put this in your Gradle script:

```
jlink {
    options = ['--bind-services', '--strip-debug', '--compress', '2', '--no-header-files', '--no-man-pages']
    forceMerge 'jakarta'
    mergedModule {
        additive = true
        uses 'javax.xml.bind.JAXBContextFactory'
    }
}
```

You will probably also need to add the following dependency:
```
    implementation 'org.glassfish.jaxb:jaxb-runtime:2.3.2'
```

Let me know if it works.

**Comment by rraumberger** [comment]
Thanks for the fast fix. Works as expected now. :+1:
