### ISSUE TITLE
Cannot derive uses clause from service loader invocation in:  .. package javax.servlet does not exist

### ISSUE THREAD

**Issue by wvc** [beryx/badass-jlink-plugin#59]
Hi,

This is my first try to getting a custom runtime built for my JavaFX 11 / Java 11 application. It depends on LogBack-classic & slf4j for logging support.  However, I'm getting the error below due to some dependency of LogBack on javax.servlet.  I'm not sure how to resolve it, but perhaps it is an issue with the beryx jlink plugin, given that I've found an issue report with roughly the same error ('Cannot derive uses .. ' ) here. However, the root cause in my case seems different:  package javax.servlet does not exist  .

> Task :createMergedModule
Cannot derive uses clause from service loader invocation in: ch/qos/logback/classic/util/EnvUtil.loadFromServiceLoader().
D:\workspaces\workspace\JFX\build\jlinkbase\tmpjars\be.kuleuven.merged.module\module-info.java:218: error: package javax.servlet does not exist
    provides javax.servlet.ServletContainerInitializer with ch.qos.logback.classic.servlet.LogbackServletContainerInitializer;

**Comment by wvc** [comment]
Hmm, I'm not sure what changed but now when I run gradlew jlink I get a different (but related) error:

 Task :createMergedModule
Cannot derive uses clause from service loader invocation in: ch/qos/logback/classic/util/EnvUtil.loadFromServiceLoader().
D:\workspaces\workspace-diamcad\DiamCAD-JFX\build\jlinkbase\tmpjars\be.kuleuven.diamcad.merged.module\module-info.java:220: error: cannot find symbol
    provides javax.servlet.ServletContainerInitializer with ch.qos.logback.classic.servlet.LogbackServletContainerInitializer;
                          ^
  symbol:   class ServletContainerInitializer
  location: package javax.servlet
1 error

**Comment by siordache** [comment]
The simplest way to get rid of the error is to include `javax.servlet-api` in your `dependencies` block:

    dependencies {
        implementation 'javax.servlet:javax.servlet-api:4.0.1'
        ...
    }


However, `javax.servlet-api` is one of logback's optional dependencies and your code probabliy doesn't need the ch.qos.logback.classic.servlet.LogbackServletContainerInitializer. As a result, you will end up with a custom runtime image containing one or more unnecessary modules.
_(If the size of the resulting custom runtime image is not important for your use case, you can use this solution and ignore the rest of this message.)_


That's why, instead of adding the `javax.servlet-api` dependency, it's preferable to customize the module descriptor of your merged module. To do this, you can first execute:

    ./gradlew suggestMergedModuleInfo


Then remove the unnecessary directives from the suggested module descriptor and include it into your Gradle build script.

For example, executing the `suggestMergedModuleInfo` task for the [badass-jlink-example](https://github.com/beryx-gist/badass-jlink-example) will print the following module descriptor:

    mergedModule {
        requires 'java.management';
        requires 'java.naming';
        requires 'java.logging';
        requires 'java.sql';
        requires 'java.xml';
        requires 'jdk.unsupported';
        provides 'javax.servlet.ServletContainerInitializer' with 'ch.qos.logback.classic.servlet.LogbackServletContainerInitializer';
    }

But for this example application, the following [mergedModule descriptor](https://github.com/beryx-gist/badass-jlink-example/blob/7ae7767cad6c21c628bcef85e06c44cbf96a5c7c/build.gradle#L28-L31) is actually all you need:


    mergedModule {
        requires 'java.naming'
        requires 'java.xml'
    }


Try to customize the mergedModule of your application in a similar way.

**Comment by danielpeintner** [comment]
I cannot reopen this issue but I would like to ask a follow-up question since I am running in a similar issue.

I started a *test* project (see https://github.com/danielpeintner/Java11Test) and tried to add dependencies step by step. After adding Apache POI I run into similar issues as described in this issue.

```
Cannot derive uses clause from service loader invocation in: org/apache/commons/compress/utils/ServiceLoaderIterator.<init>().

error: module not found: java.xml.bind
```

Hence, I tried to use `gradlew suggestMergedModuleInfo` which reports

```
mergedModule {
    requires 'java.xml.bind';
    requires 'java.xml.crypto';
    requires 'java.logging';
    requires 'java.xml';
    requires 'java.desktop';
    requires 'java.datatransfer';
    requires 'java.security.jgss';
    requires 'jdk.javadoc';
}
```

I did add this but now I run into another issue

```
> Task :createMergedModule FAILED
error: module not found: java.xml.bind
```

Is there any best practice one can follow?

I can run the project just fine when using `gradlew run` or in my IDE.

Thanks for any insight!

**Comment by siordache** [comment]
`java.xml.bind` is one of the modules deprecated in Java 9 and removed from the JDK in Java 11. You need to add `org.glassfish.jaxb:jaxb-runtime:2.3.2` to the list of dependencies in build.gradle.

See [this StackOverflow thread](https://stackoverflow.com/questions/48204141/replacements-for-deprecated-jpms-modules-with-java-ee-apis) for more info and best practices concerning the replacements for the removed modules.

**Comment by danielpeintner** [comment]
Thanks for your quick feedback. I did try to use the approach mentioned in your link or [here](https://www.jesperdj.com/2018/09/30/jaxb-on-java-9-10-11-and-beyond/).

However, I don't think this is the issue.

> java.xml.bind is one of the modules deprecated in Java 9 and removed from the JDK in Java 11. You need to add org.glassfish.jaxb:jaxb-runtime:2.3.2 to the list of dependencies in build.gradle.

`implementation 'org.glassfish.jaxb:jaxb-runtime:2.3.1'` has been there before and the JAXB tests were working.

The issues I am running into appear once I add Apache POI dependency. Before I did not even need `mergedModule` .
This [commit](https://github.com/danielpeintner/Java11Test/commit/f746a87553f07d5eb507ddbc9fe07c042ba6009a) works just fine... mhhh

**Comment by siordache** [comment]
The plugin incorrectly suggests that 'java.xml.bind' is required by the mergedModule. Just remove [this line](https://github.com/danielpeintner/Java11Test/blob/a458ac5acf8742bbff885e4b3a3235272e7469cc/build.gradle#L78) from `mergedModule` and it should work.

I don't have a best-practice advice for this use case. A bit of trial and error is still required.
