### ISSUE TITLE
Request: UserJvmOptionsService replacement for users to alter the JVM settings

### ISSUE THREAD

**Issue by Merudo** [beryx/badass-jlink-plugin#80]
As you know, the old `jpackage` supported `UserJvmOptionsService` which could be used in self-contained applications to alter the JVM settings.

The user could add launch arguments which would be recognized by `UserJvmOptionsService`. This was handy for example to change the default java stack size or the default memory.

I believe the key classes were `UserJvmOptionsService`, `LauncherUserJvmOptions` and `PreferencesUserJvmOptions`.

Having an option similar to  `UserJvmOptionsService` in `Badass JLink Plugin` would greatly extend the utility of the plugin.

**Comment by siordache** [comment]
I would gladly add this feature to the plugin, but this is not possible as long as `jpackage` doesn't support it. A few months ago, @lenborje [requested such a feature](https://www.mail-archive.com/core-libs-dev@openjdk.java.net/msg58481.html). You should revive his thread so that it gets the attention it deserves. You can also point to this feature request in the [thread initiated by Mark Reinhold](https://www.mail-archive.com/core-libs-dev@openjdk.java.net/msg61154.html) a couple of days ago.
